### ISSUE TITLE
License discrepancy

### ISSUE THREAD

**Issue by pointyointment** [PRouzeau/OpenSCAD-Delta-Simulator#2]
In the repo you have GPLv3 for the LICENSE file, while the comments at the top of the simulator code and the info that the simulator renders both say GPLv2.

**Comment by PRouzeau** [comment]
Thank you. I am always afraid of the compatibility problem between GPLv2 and GPLv3, so I think I will make the release GPLv2 or any later version, which may be the most compatible within GPL.

**Comment by PRouzeau** [comment]
Set GPLv2 or any other later version
